/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE OBSTACLE_DISTANCE PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Obstacle distances in front of the sensor, starting from the left in increment degrees to the right
*/
public class msg_obstacle_distance extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_OBSTACLE_DISTANCE = 330;
    public static final int MAVLINK_MSG_ID_OBSTACLE_DISTANCE_CRC = 201;
    public static final int MAVLINK_MSG_LENGTH = 22;
    private static final long serialVersionUID = MAVLINK_MSG_ID_OBSTACLE_DISTANCE;


      
    /**
    * Timestamp (microseconds since system boot or since UNIX epoch)
    */
    public long time_usec;
      
    /**
    * Class id of the distance sensor type.
    */
    public short estimator_type;
      
    /**
    * Distance of obstacles in front of the sensor starting on the left side. A value of 0 means no obstacle. In a array element, each unit corresponds to 1m.
    */
    public short distances[] = new short[12];
      
    /**
    * Angular width in degrees of each array element.
    */
    public short increment;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_OBSTACLE_DISTANCE;
        packet.crc_extra = MAVLINK_MSG_ID_OBSTACLE_DISTANCE_CRC;
              
        packet.payload.putUnsignedLong(time_usec);
              
        packet.payload.putUnsignedByte(estimator_type);
              
        
        for (int i = 0; i < distances.length; i++) {
            packet.payload.putUnsignedByte(distances[i]);
        }
                    
              
        packet.payload.putUnsignedByte(increment);
        
        return packet;
    }

    /**
    * Decode a obstacle_distance message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.time_usec = payload.getUnsignedLong();
              
        this.estimator_type = payload.getUnsignedByte();
              
         
        for (int i = 0; i < this.distances.length; i++) {
            this.distances[i] = payload.getUnsignedByte();
        }
                
              
        this.increment = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_obstacle_distance(){
        msgid = MAVLINK_MSG_ID_OBSTACLE_DISTANCE;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_obstacle_distance(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_OBSTACLE_DISTANCE;
        unpack(mavLinkPacket.payload);
    }

            
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_OBSTACLE_DISTANCE - sysid:"+sysid+" compid:"+compid+" time_usec:"+time_usec+" estimator_type:"+estimator_type+" distances:"+distances+" increment:"+increment+"";
    }
}
        